/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
[2024-12-19 13:57:14,368] torch.distributed.run: [WARNING] 
[2024-12-19 13:57:14,368] torch.distributed.run: [WARNING] *****************************************
[2024-12-19 13:57:14,368] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2024-12-19 13:57:14,368] torch.distributed.run: [WARNING] *****************************************
xFormers not available
xFormers not available
xFormers not available
xFormers not available
[2024-12-19 13:57:18.038] [ouster::sensor] [info] parsing legacy metadata format
[2024-12-19 13:57:18,045][    INFO] {'bs': 4,
 'dataset': 'm3ed',
 'encoder': 'vits',
 'epochs': 120,
 'img_size': 518,
 'local_rank': 0,
 'lr': 5e-06,
 'max_depth': 90.0,
 'min_depth': 0.001,
 'ngpus': 2,
 'port': 20596,
 'pretrained_from': '../depth_anything_v2_vits.pth',
 'save_path': 'exp/m3ed'}

[2024-12-19 13:57:18.049] [ouster::sensor] [info] parsing legacy metadata format
[2024-12-19 13:57:18.069] [ouster::sensor] [info] parsing legacy metadata format
[2024-12-19 13:57:18.073] [ouster::sensor] [info] parsing legacy metadata format
Traceback (most recent call last):
  File "/data1/liangao/AlanLiang/Projects/MVLM/Depth-Anything-V2-M3ED/metric_depth/train.py", line 219, in <module>
    main()
  File "/data1/liangao/AlanLiang/Projects/MVLM/Depth-Anything-V2-M3ED/metric_depth/train.py", line 98, in main
    model.load_state_dict({k: v for k, v in torch.load(args.pretrained_from, map_location='cpu').items() if 'pretrained' in k}, strict=False)
  File "/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../depth_anything_v2_vits.pth'
Traceback (most recent call last):
  File "/data1/liangao/AlanLiang/Projects/MVLM/Depth-Anything-V2-M3ED/metric_depth/train.py", line 219, in <module>
    main()
  File "/data1/liangao/AlanLiang/Projects/MVLM/Depth-Anything-V2-M3ED/metric_depth/train.py", line 98, in main
    model.load_state_dict({k: v for k, v in torch.load(args.pretrained_from, map_location='cpu').items() if 'pretrained' in k}, strict=False)
  File "/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../depth_anything_v2_vits.pth'
[2024-12-19 13:57:19,399] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 3364124) of binary: /home/liangao/miniconda3/envs/openmmlab/bin/python3
Traceback (most recent call last):
  File "/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/liangao/miniconda3/envs/openmmlab/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-12-19_13:57:19
  host      : server
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 3364125)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-19_13:57:19
  host      : server
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3364124)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
